display_name: FlClashY

packager: vaniley
packagerEmail: vaniley@users.noreply.github.com
license: GPL-3.0

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClashY
  - Clash
  - Proxy

generic_name: FlClashY

group: Applications/Internet

startup_notify: true
