// GENERATED by setup.dart from core/constant/version.go — do not edit by hand
// ignore_for_file: constant_identifier_names

/// Embedded mihomo version (see core/constant/version.go).
const String kCoreVersionFromSource = 'v1.19.28';
