display_name: FlClashY
package_name: FlClashY
maintainer:
  name: vaniley
  email: vaniley@users.noreply.github.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-1
  - libkeybinder-3.0-0

keywords:
  - FlClashY
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClashY

categories:
  - Network

startup_notify: true
