script_template: inno_setup.iss
app_id: 9023088E-DCCC-4BF1-81A4-EDC21B84FB82
app_name: FLClashY
publisher: vaniley
publisher_url: https://github.com/vaniley/FlClashY
display_name: FLClashY
executable_name: FLClashY.exe
output_base_file_name: FLClashY.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: ru
  - lang: en
privileges_required: admin
